# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# There are two btc related configs
# 1. [btc-config] is config for btc full node which should have transaction indexing
# enabled. This node should be synced and can be open to the public.
# 2. [btc-signer-config] is config for bitcoind daemon which should have only
# wallet functionality, it should run in separate network. This bitcoind instance
# will be used to sign psbt's
[btc-config]
# Btc node host
host = "testnet3.btc.scalar.org:80"
# Btc node user
user = "mike"
# Btc node password
pass = "apd3g41pkl"
# Btc network (testnet3|testnet4|mainnet|regtest|simnet|signet)
network = "testnet3"

[[evm-config]]
# Evm chain id
chain-id = 11155111
# Evm chain name
chain-name = "ethereum-sepolia"
# Evm chain rpc url
rpc-url = "https://eth-sepolia.g.alchemy.com/v2/nNbspp-yjKP9GtAcdKi8xcLnBTptR2Zx"
finality-override = "confirmation"
# Evm chain address
smart-contract-address = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"    

[server-config]
# The address to listen on
host = "127.0.0.1"

# The port to listen on
port = 9791

# Read timeout in seconds
read-timeout = 15

# Write timeout in seconds
write-timeout = 15

# Idle timeout in seconds
idle-timeout = 120

# Max content length in bytes
max-content-length = 8192
# 
access-token = ""
[metrics]
# The prometheus server host
host = "127.0.0.1"
# The prometheus server port
port = 2112
