services:
  bitcoin-testnet4:
    image: mocacinno/btc_testnet4:bci_node
    privileged: true
    container_name: bitcoin-testnet4
    volumes:
      - ../example/bitcoin.${NETWORK:-testnet}.conf:/root/.bitcoin/bitcoin.conf
      - ./run.sh:/run.sh
    entrypoint: /run.sh entrypoint
    # entrypoint: ["sleep", "infinity"]
    # command:
    #   - -testnet
    #   - -rpcbind=${RPC_BIND:-127.0.0.1:18332}
    #   - -rpcuser=${RPC_USER:-user}
    #   - -rpcpassword=${RPC_PASS:-password}
    #   - -rpcallowip=${RPC_ALLOWIP:-127.0.0.1/0}
    #   - -datadir=${DATADIR:-/root/.bitcoind}
    #   - -server=${SERVER:-1}
    #   - -txindex=${TXINDEX:-1}
    #   - -connect=${CONNECT:-0}
    #   - -daemon=${DAEMON:-1}
    ports:
      - "48332:18332"
      - "48333:18333"

  protocol-signer:
    container_name: protocol-signer
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: "scalarorg/protocol-signer:latest"
    ports:
      - "9791:9791"
      - "2112:2112"
    volumes:
      - ../example/config.toml:/home/protocol-signer/.signer/config.toml:Z
    entrypoint: ["protocol-signer", "start"]
    command: ["--config", "/home/protocol-signer/.signer/config.toml"]
